name: HamsterCurrency
version: ${project.version}
main: cn.hamster3.currency.HamsterCurrency
api-version: "1.16"
authors: [Hamster3]
description: 仓鼠的多货币支持
website: https://www.hamster3.cn/

depend:
  - HamsterAPI

softdepend:
  - HasmterService

commands:
  HamsterCurrency:
    aliases: [hCurrency, currency]

permissions:
  currency.add:
    default: op
  currency.take:
    default: op
  currency.set:
    default: op
  currency.look:
    default: true
  currency.look.other:
    default: op
