name: HamsterCurrency
version: ${project.version}
main: cn.hamster3.currency.HamsterCurrency
authors: [Hamster3]
description: 仓鼠的多货币支持
website: https://www.hamster3.cn/

load: STARTUP
api-version: "1.16"

depend:
  - HamsterAPI

softdepend:
  - HasmterService
  - PlaceholderAPI
  - Vault

commands:
  HamsterCurrency:
    aliases: [hCurrency, currency]
  balance:
    aliases: [bal, seeMoney, money]
  balanceTop:
    aliases: [baltop]
  payMoney:
    aliases: [pay]

permissions:
  currency.import:
    default: op
  currency.add:
    default: op
  currency.take:
    default: op
  currency.set:
    default: op
  currency.look:
    default: true
  currency.look.other:
    default: op
  currency.top:
    default: op
